kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive --remote
  - cd assets/resources/MathJax
  - git checkout $(git tag | /bin/grep '^2' | sort -V | tail -1)

- name: docker
  pull: if-not-exists
  image: plugins/docker
  settings:
    pull: false
    pull_image: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    registry:
      from_secret: docker_registry

